version: "3"
services:
  api:
    image: node:11.13.0-alpine
    container_name: api
    volumes:
      - .:/app
    environment:
      - NODE_ENV=dev
      - SECRET=Ks10daK3g
      - WISP_PROBLEMS_URL=http://localhost:8080
    working_dir: /app
    command: npm run start:local
    network_mode: host
  mongo:
    container_name: mongo
    image: mongo
    network_mode: host
    logging:
      driver: none